/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>


enum class LogLevel {
  Trace,
  Debug,
  Info,
  Warn,
  Error,
};


extern "C" {

void log(const char *context, const char *message, LogLevel log_level);

}  // extern "C"
