name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang ninja-build llvm

      - name: Configure coverage
        run: cmake --preset coverage

      - name: Run tests and coverage
        run: cmake --build --preset coverage --target coverage